### ISSUE TITLE
Meet►Sprint►W22 for V²Shop-Midwest 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#116]
- [x] What is the comment on V²Site and Plan → In general you are happy with it
- [x] Add Tom's GitHub account → tcaswelch
- [x] Add Karen's GitHub account → kcaswelch
- [x] Review [Building a Big Web Site on GitHub](https://github.com/V-Squared/V-Squared.github.io/issues/48#issuecomment-217838186) → Seems Straightforward. Wishlist seems OK. 
  - Question about Angular Apps: 
- [x] Review → #106 (particularly order of development and page structure) → accepted
  - [x] HC: Add DIY Articles and Configurations to V²DIY
- [x] Brainstorm on creating Issues to work on next
- [x] HC: Start working on:
  - Create the Structure of Spreading
  - Move the already existing Know How and DIY Articles from the Wiki Pages
  - Discuss and tune structure
  - Prioritize Articles
  - Work down Article one by one
  - Create Products Board and Pages as per structure
  - Start building content on Products Pages
  - Create Issues on Evaluating that can be done without ViCase Housing ready yet
- [x] #118

**Comment by bcaswelch** [comment]
All ticks are checked.
