### ISSUE TITLE
Bug: Fix redundant V²Plan to avoid data loss! 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#128]
- [x] HC, LC: Analyze the bug and report it here
- [x] LC: Fix it
- [x] LC: The edit button of new place does not open proper Article. Needs fix.
- [x] HC: Move content I have edited to the new pages
- [x] HC: check that it is fixed, then close issue
# How the Problem Shows
- I used a bookmark to go to: http://v-squared.github.io/v2-Plan/dashboard/
- I edited the page
- I reloaded the page and checked that the edit was fine
- later I navigated to the same page using the Board Bar
  - not noticed by me, I landed on a slightly different URL: http://v-squared.github.io/plan/dashboard/
- All my changes were lost
# What happened
- we currently host two web sites of plan in parallel:
  - https://v-squared.github.io/plan/ (new)
  - https://v-squared.github.io/v2-Plan/ (old)
- if you make changes in one, it does not show in the other
# What need to be done now
- Create a "We moved" Message
  - Replace V²Plan → "!!! We moved !!!"
  - Change back ground color to screaming red
  - Change subtitle to: New address → http://v-squared.github.io/plan/ If you were to make edits now, they will be deleted later. So do not do it!
    - make the link click able
# What need to be done later
- delete the whole v2-Plan repository

**Comment by bcaswelch** [comment]
Yep, makes sense.
