### ISSUE TITLE
Meet►Sprint►W23 for V²Shop-Midwest 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#129]
# Preparing
- [x] HC: Create Focus this week in Dashboard
  - [x] LC:  → Bug: Fix redundant V²Plan to avoid data loss! #128 
  - [x] HC: Move content to correct address → http://v-squared.github.io/plan/dashboard/
- [x] HC: Archive all closed issued in both Scrum Boards
- [x] HC: Review issues in _Developing_ and find the ones that the Assignee forgot to close
- [x] HC: Transfer all notes into issues into backlog
- [x] HC: Pick Issues for this week, Check assignments, move to "This Sprint" Column
  - Note: This is a crutch to get going now. Ideally each developer picks their own issues.
# Meeting
- [x] Meeting: 8:30 pm on Monday LV time; 11:30 am China time on Tuesday
- [x] Note: The Development column should be empty at Sprint Kick Off meeting. Lets try to achieve this next Kick Off
- [x] I am still overwhelmed as Scrum Master
  - If you are not busy, talk to me on what to work on or create an issue so to let me know what you chose to work on and then work it down. I am working much overtime to get on top of things.
- [x] Explaining Sprint:
  - One Assignee only: He is responsible
  - Delegation with @ mentions
  - Meaning of all columns on the Scrum Board
  - We are not explaining everything now, but enough to get you going this week
  - How to filter the Scrum board
  - How to find your work
  - The purpose of two Scrum boards:
    - [V² Scrum Board](https://waffle.io/V-Squared/V-Squared.github.io) (Overview to all work, including Production)
    - [Production Scrum Board](https://waffle.io/V-Squared/v2-Production) (Overview Production only)
  - Importance and Speed of Daily Stand Ups
    - get motivated by cool demos of others or praise of your cool demo
    - e.g. identify hang ups early (Example DIY Page Structure)
- [x] Going through proposed assignments
  - Filter by each assignee, then go through all assignments
  - On each assignment the assignee must agree or reject
  - Repeat until finished
# Wrapping Up
- [x] What time daily stand ups? 8:30 pm? They are supposed to be very short, about 2 minutes per person.
- [x] Agree on next weeks Sprint Kick Off: Sunday, 8:30 pm LV time?

**Comment by bcaswelch** [comment]
Went well!

**Comment by VillageHubertChen** [comment]
Thank you for the feedback. It will be great if you can give feedback each time, including things we can improve.

**Comment by bcaswelch** [comment]
Sounds good.
