### ISSUE TITLE
Increase Container Width on V² 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#140]
- [x] HC: Write User Story
- [x] Implement
- [x] Self Test
- [x] Trigger HC for testing
- [x] HC: Final test, close issue
# User Story

As a **Power Reader** of V² Articles I have a big screen and I am using _Article-Bar_ and _Contents-Bar_. Before you increased the _Container Width_ my Article Width was simply too narrow. This was annoying, as I had a big screen where space was wasted left and right. Your new bigger container width solves the problem. Thank you.
# References
- → User Collapsable Menu #110 
- → Automatic Table of Contents Generation #130 
- → Increase Container Width on V² #140

**Comment by bcaswelch** [comment]
Bigger container is good, but a lot of people read on their tablets which use a narrower screen. Won't be an issue though due to the responsive design.

**Comment by VillageHubertChen** [comment]
Exactly! This added feature will be invisible to tablet users. But it makes a big difference to people who have a screen bigger than 1400 pixels. Many desktop users have Full HD, which is 1920 px wide. The bigger container gives people with bigger screen better usability without sacrificing usage on the small screen.

**Comment by VillageHubertChen** [comment]
Update from Lukas: The larger container is finished. But before pushing he will add a feature that the Article can not become too wide. So I guess by tomorrow morning you can test it out will all related three issues completed.

**Comment by LukasChen** [comment]
The big container is ready for review.
Look at this link: http://localhost:8080/plan/system/solving-problems/

**Comment by LukasChen** [comment]
@bcaswelch The big container is ready for review.
Look at this link: https://v-squared.github.io/plan/system/solving-problems/

**Comment by LukasChen** [comment]
@VillageHubertChen  Please Review

**Comment by VillageHubertChen** [comment]
# Bug Report
- [x] Tooltips to Readiness-Bar are broken
- [x] Create collapse button in style of readiness step, place same way as readiness-bar
  - ask me to make a drawing the moment when you are implementing this one

**Comment by bcaswelch** [comment]
Looks great, I'll keep an eye on the bugs reported.

**Comment by VillageHubertChen** [comment]
@bcaswelch We shall finish today. Note the related bug and feature issues. By the end of our day there should be a marked improvement in usability. Especially creating Article issues will become much easier :-)

**Comment by VillageHubertChen** [comment]
# Bug Report

- [ ] On Mobile screen the two collapse buttons need to be hidden
