### ISSUE TITLE
Bug►Breadcrumb Broken Across Site 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#142]
# How it shows

On all pages the bread crumbs read: "V² > Plan"
# Additional Information

Was working before moving V²Plan

**Comment by bcaswelch** [comment]
R&U

**Comment by VillageHubertChen** [comment]
Thanks for leaving the "R&U" comment. I will much, much appreciate if you can leave any kind of comment to each issue with notification. Then I know you got the message. Things like "R&U" or "Agreed" of "Closed" or similar will end the conversation.

**Comment by bcaswelch** [comment]
Sounds good.
