### ISSUE TITLE
Bug►Board Links switch to HTTP 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#143]
# How it Shows
1. You are happily browsing V² fast (on HTTPS)
2. You change the Board (Clicking on a button in the board menu)
3. You are sad to browse V² slowly (on HTTP)

**Comment by LukasChen** [comment]
DONE :tada:

**Comment by VillageHubertChen** [comment]
Confirmed. Works like a charm :+1:
