### ISSUE TITLE
Bug: Markdown in Abstract in Article is not rendered 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#148]
# How the Problem Shows

The abstract in this article → [V² > Plan > System > Solving Problems](https://v-squared.github.io/plan/system/solving-problems/) shows asterisks enveloping words rather than render the words italic.

**Comment by bcaswelch** [comment]
R&U

**Comment by VillageHubertChen** [comment]
@bcaswelch Thanks for diligently answering all comments. Very appreciated. The same time I want to make sure your ears are not ringing with all the traffic going on. This issue was created by me and assigned to Lukas. You were not meant to be bothered. Did you find this issue by chance or did you got a notification? If you got a notification, any changes we can do so you:

Only get notified:
1. If you are assigned to issue
2. If you are mentioned with @mentions

Or do you like to be in the loop until the time traffic becomes too much?

**Comment by bcaswelch** [comment]
Yeah this appeared in a notification. I'll only answer to the ones I get a mention in, will make things simplier. I'll ready through all of my notifications still to stay up to date, just won't reply to all of them.

**Comment by VillageHubertChen** [comment]
@bcaswelch That will work.

**Comment by VillageHubertChen** [comment]
## Note for Debt.Docu

Markdown is now working in Subtitle and Abstract. Paragraph by empty line is not supported. But you can simulate it with <br>&nbsp;&nbsp;&nbsp;
