### ISSUE TITLE
Bug: Issues missing in Milestones 2016W23

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#150]
# How Problem Shows

When creating a statistic of our progress I found that adding all issues up in milestone the number reached 110 versus we have 150 Issues.
# What caused the Problem

Many issues have no Milestone
# Fixing the Problem
1. Search in Issue Search field: 
   1. is:issue is:open no:milestone 
   2. is:issue is:closed no:milestone 
2. Open each issue and assign milestone

**Comment by bcaswelch** [comment]
Okay

**Comment by VillageHubertChen** [comment]
All Issues assigned to Milestones
