### ISSUE TITLE
Write Introduction to V² (Features of V² Home Page)

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#23]
- [x] HC: Write copy for Introduction
- [x] @LukasChen Transfer copy to V² Home Page. Add the visuals that we already have. Leave the visuals not ready yet.
- [x] @LukasChen  Add a Layout feature that the Introduction is separate from the Portfolio part of the Web Site. Maybe by making the horizontal navigation bar go all across the page, passing into the margin and by giving it a thick top line? When done trigger HC for review
- [x] Add Value Proposition
- [x] Break up the Layout into four parts:
  1. Introduction to V²
  2. Value Proposition of V²
  3. Video of V²
  4. Implementation of V²
  5. Overview of V²
  6. Team (picture we made for campaign)
- [x] Rewrite "Delivering all pieces of the Puzzle" → "The Big Picture of V²"
- [x] HC: Complete writing of copy of Introduction.
- [x] GI: Review
## Related Tasks in Related Issues
- #41 
- #53 
- #123
- Timeline in Introduction #30
- Closing V² Home Page #33
- How the V² Home Page works #21
- Site Navigation Bar #36
# Introduction to V²
## V² Modular PC Open Source

Upgradable Mini and All-In-One PC

V-Squared is an Open Source Non-Profit Standard Initiative and Community on [GitHub.com/V-Squared](https://github.com/V-Squared). We develop and publish standards, blueprints, know how articles, white papers, workflows, and apps to make Mini and All-In-One Computer modular, ugradable and easy to repair. For the benefit of the individual user as well as the DIY Community and PC Industry as a whole.
# Open Source
## GitHub

We host all projects, web sites and know how on the leading Project Hosting Web Site. Project management is done with its ticketing system "GitHub Issues" .

Open Source Initiative
V² Initiative is compliant with all Guidelines of the Open Source Initiative. Use V² or contribute to it with confidence.
## Open Hardware

All our open source hardware projects are compliant to the guidelines of the Open Source Hardware Association and thus earned the Open Source Hardware Logo.
## CC

Creative Commons License is the most free to copy license in the Open Source Hardware world. Copy our designs with confidence for any intended use.
## Arduino

The leading Open Source Micro Controller Platform. We use it for advanced embedded functions. Easy to develop and document. Low cost in mass production.
# Value Proposition of V²
## The Missing Standard

Desktop Computer were the best selling PC form factor, because the ATX standard made them to be lowest cost, easy to build and upgrade. But this de facto standard is 30 years old and was not updated to fit the needs of Mini and All-In-One Form Factor. The V² Standard lowers cost, increases performance and simplifies upgrading. In doing so V² is breathing new life into Mini and All-In-One PCs.
## Modular PC

As a user the modular approach allows you to configure your Mini or All-In-One PC with exactly the features you want. And when your Modular PC gets older you only need to upgrade the bottleneck part instead of buying an entire new PC. As a dealer you enjoy increased availability while reducing your inventory. As a maker the modular approach saves cost and development time.
## Trailblazer Products

Specifications of a new standard on the web are one thing. Having a finished product in hand for testing is quite another. This is where Trailblazer Products come in: **1)** Early adopters can buy Trailblazer Products for testing / reviewing or simply personal use before mass production becomes available. **2)**  Demo the value of V² Standard with real products  **3)** Funding of V² Standard development.
## Hero Layout
- http://mdbootstrap.com/live/_products/Landing-Page/index.html#sec-best-features
# Video

Show the best Video we have of ViCase
# Implementation of V²
## Open Source Accelerator

Establishing a new standard was time consuming in the past. V² speeds up the process by fully embracing the best of Open Source and Rapid Development workflows. Hover over the Logos to learn more ...
## Fluid Form Factor

A traditional Desktop, Mini or All-In-One PC is frozen in their Form Factor. Instead you can change the Form Factor of your V² Modular PC. Explore how by using the buttons on the App. This opens completely new _Use Cases_ for you. E.g. an All-In-One PC is now easy to bring with you, as all you need to bring is its Mini PC Module.
## Zero Cost

To further speed up the introduction of the V² Standard we are introducing it at Zero Cost, as in free beer, and it will always stay that way. In other words, license for commercial use, license of the logo or product certification are all available at $0 US cost.
## Timeline

We began research of V² Modular PC in 2011 and started prototyping in 2013. Now in 2016 we are in production. Please hover / tab on the timeline for more details.
- Issue #30
## Usable Work in Progress

Our Trailblazer Products are developed compliant to the V² Standard. We are now in the process of moving our standard documents to GitHub. The GitHub Ribbon and the Progress Bar inform you of the status and expected improvements. Hover or tab on the demo above for more details ...
- Issue #31 
## V² in Action Gallery
- Find a few of the greatest pictures we have
- Make a simple good looking Gallery
- Each picture has Title and Subtitle
- Use the Gallery you already design for our product home page
## V² delivers all pieces of the puzzle

Traditional _Standards_ deliver the standard only, leaving it up to the developer, manufacturer and user to compile and create the missing pieces. Instead V² uses a community approach to develop together and subsequently publish all _Missing Pieces_ as Open Source. Hover or tab on the _Pieces_ for more information.
## V² Serves as a Library Shelf

This V² Site serves as a _Library Shelf_ to publish all Know How on V² Modular PC in the form of cataloged articles. The 9 pieces which make up V² are represented in the _V² Modular PC Shelf_ by 9 _Boards_. Each _Board_ holds _Books_ which are _Article Collections_. Hover or tab on the call-outs for more information.
- Issue #22 
# Explore V²

---
# Introduction answers the key questions
## Q: What is it?

Modular PC Open Source. This section explains it in enough detail to get reader going.
## Q: Where do we want to go?

We want to make V² Modular PC Open Source. Explained in the next section: "Making V² Modular PC Mainstream"
## Q: How to go there?

By delivering all pieces of the puzzle
## Q: What is our magic bullet?

Providing everything in Open Source speeds up the process.
# Reference
- #41 
- #53 
- #123
- Timeline in Introduction #30
- Closing V² Home Page #33
- How the V² Home Page works #21
- Site Navigation Bar #36

**Comment by VillageHubertChen** [comment]
# Feedback Georg: Add a time line ...

... showing:
1. How far have we come already
2. Show all the things that are still going to happen
3. Make it an interactive timeline, same as the other Mini Apps
4. It must be clear we are pre-ordering in May and shipping in June
5. Make it easy to move the "today" cursor

**Comment by VillageHubertChen** [comment]
# Feedback Georg:
- New structure of Home Page works well
- New Introduction text works
- Layout ideas seem good. Need to see final implementation though.

**Comment by VillageHubertChen** [comment]
# What we added since last review
- Modular PC
- Video
- Fluid Form Factor
- V² in Action Gallery
- V² Serves as a Library Shelf

**Comment by georgillies** [comment]
# Also add to Introduction
- Configurator
- Computer DIY Know How

**Comment by VillageHubertChen** [comment]
# Reply to Georg's Suggestion

Agreed. We should add each (Configurator | DIY Know How) once each item becomes available and can be linked.
