### ISSUE TITLE
Add Links of the Page Sections in the Puzzle Tooltips

### ISSUE THREAD

**Issue by LukasChen** [V-Squared/V-Squared.github.io#34]

**Comment by VillageHubertChen** [comment]
# Change Request after Review
- [x] Change Link Color to Highlight 2
- [x] Fix bug of wrong position of tooltip when window width is minimal
- [x] Add arrow → in front of link
- [x] Check that it works on Tablet

**Comment by VillageHubertChen** [comment]
All done :tada:
