### ISSUE TITLE
Library Metaphor for V² Navigation

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#44]
- [x] Develop → [Library Metaphor](#issuecomment-217384263)
- [x] Proof read → [Library Metaphor](#issuecomment-217384263)
- [x] Modify → #42 to reflect Library Metaphor
- [x] Find a place where to put this Article on V² Site → #48

**Comment by VillageHubertChen** [comment]
# Library Metaphor for Navigation

# Table of Contents
- [Library Metaphor Explained](#explained) ← NEW
- [Tooltips teach Library Metaphor](#tooltips-metaphor) ← NEW
- [Mapping of Metaphor Element to Nav Bar](#maping)
- [Examples](#examples)
- [Illustration of Library Metaphor](#illustration)

# Library Metaphor Explained <a name="explained"></a>

Finding Articles of your interest on the V² Site is the same problem you are faced with when entering a library. You already know how to do that in a Library. So we modeled the _V²Site Navigation_ after the _Library Metaphor_. 

| Name | Explanation |
| :-: | :-- |
| Shelf | **Book Shelf:** Imagine a Library where every shelf only contains books to one topic. The top of the shelf has a big label of the topic's name. The V² Site is the _Book Shelf_ or short _Shelf_. |
| Board | **Board of Shelf:** Each _Board_ only contains books to the same topic. We color coded each to help you find it faster the next time. |
| Book | We bind collection of Articles on the same topic into one _Book_. |
| Article Collection | Small _Books_ only contain one collection of Articles. However in big books we group Articles in _Article Collection_ once there are more than 10 Articles. This helps you to keep an overview. |
| Article | Writing on one topic of about 1 ... 15 pages lengths |
| ToC | Table of Contents. Linked List of all Heading 1 of the Article |

# Tooltips teach Library Metaphor <a name="tooltips-metaphor"></a>

| Nav Bar | Tooltip |
| :-: | :-- |
| Board | This is the Board Navigation Bar. Each of its Menu Items represent a colored board in the V² Modular PC Shelf |
| Book | This is the Book Navigation Bar. Each of its Menu Items represents a Book which is a collection of Articles. |
| Article | This is the Article Navigation Bar. Click on the Article of your Interest to display it. |
| Table of Content | The Table of Content Bar lists you all Top Level Headings of this Article. Click on a Heading to scroll the Article to it. |

**Tip:** This is the link to the info Icon that is invoking the tooltip: Icon: https://design.google.com/icons/#ic_info 

# Mapping of Metaphor Element to Nav Bar <a name="mapping"></a>

| Level | Metaphor | Nav Bar | Nav Bar Placement |
| :-: | :-: | :-- | :-- |
| 0 | Shelf | Shelf Bar | Drop Down Menu from top |
| 1 | Board | Board Bar | Horizontal Navigation Bar above Jumbotron. Boards are color coded |
| 2 | Book | Book Bar | Horizontal Navigation Bar under Jumbotron |
| 3 | Article Collection | Article Bar | Vertical Navigation Bar left to body |
| 4 | Article | Article Bar | Vertical Navigation Bar left to body |
| 5 | ToC | ToC Bar | Vertical Navigation Bar right to body |

[^Shelf]: Right now we only have one _Shelf_, which represents the: _V² Modular PC_. As such we do not need yet the drop down menu to switch between shelves. This is reserved for future growth of the _V² Initiative_, after the success of the _V² Modular PC_.

**Note:** The _Article Bar_ can contain one or two levels of navigation. In case of one level it is a simple list. In case of two levels it is a structured list with two levels.

## 6 Levels in Design, 5 Levels implemented now

We are counting 6 Levels now as we show the placements of the various Navigation Bars. However at this time the Shelf Bar is not used yet, so while the design offers 6 Levels of Navigation, the current implementation uses only 5 Levels of navigation

# Examples <a name="examples"></a>

## 4 Level Navigation Example
- **Path:** Plan►System►Reference►Table of Contents
- Only 4 Levels are visible in the UI now, as the _Shelf_ is always default

| Level | Name | Menu Item | Notes |
| :-: | :-: | :-: | :-- |
| 0 | Shelf | V² Modular PC | is default while V² has only one _Shelf_ |
| 1 | Board | Plan | Plan is one of 9 _Boards_ in the _Shelf_ of the _V² Modular PC_ |
| 2 | Book [^Book] | System | The Book contains all Articles to V² Plan System |
| 3 | Article | V² Plan Reference | V² Plan System is explained in 9 Articles |
| 4 | ToC | Table of Contents | Linked List of each Heading 1 of the Article |

[^Book]: Collection of Articles

## 5 Level Navigation Example
- **Path:** Products►ViPC►ViPC 750►Features►Fluid Form Factor
- Only 5 Levels are visible in the UI now, as the _Shelf_ is always default

| Level | Name | Menu Item | Notes |
| :-: | :-: | :-: | :-- |
| 0 | Shelf | V² Modular PC | is default while V² has only one _Shelf_ |
| 1 | Board | Products | Products is one of 9 _Boards_ in the _Shelf_ of the _V² Modular PC_ |
| 2 | Book [^Book] | ViPC | Each Product Family is grouped in a Book |
| 3 | Article Collection | ViPC 750 | Each Product is a group of Articles |
| 4 | Article | Features | Each Article is one Product Page, e.g. Specs, ... |
| 5 | ToC | Fluid Form Factor | Each Heading 1 of the Article |

# Illustration of Library Metaphor <a name="illustration"></a>
- Made in SVG, using v2-Tooltip
- Two parts of drawing
  - **Top:** Screen Shot of V² Article, showing all levels of Navigation
  - **Bottom:** Book Shelf Metaphor
- Curved Call Out Lines. They connect same item in Snap Shot versus Metaphor
- Call Out Line has a Call Out Number in the middle. Hovering / tapping will reveal v2-Tooltip

**Comment by LukasChen** [comment]
Read and agree :ok:

**Comment by VillageHubertChen** [comment]
# List of Things Added
- Library Metaphor Explained 
- Tooltips teach Library Metaphor in Nav Bars
- Changed Section Bar to ToC Bar (Table of Contents Bar)

**Comment by VillageHubertChen** [comment]
All done. Closed.
