### ISSUE TITLE
Multi Level Breadcrumb from book-bar.yml file

### ISSUE THREAD

**Issue by LukasChen** [V-Squared/V-Squared.github.io#57]
- [x] Create Issue for this project
- [x] Express what is the problem
- [x] Find references that deal with solving the problem
- [x] Study references. Apply new solutions until find a method that works
- [x] Clean up the code
- [x] push new version, trigger HC for testing
- [x] close issue after test passed
# How the breadcrumb works now

Each Article has a YAML front matter with the breadcrumb attribute. It looks like this:

```
breadcrumb: system
```

My Liquid template is looping through all articles and generates the bread crumb.

site.pages contains the URL of each article. To access it: 

``` php

{% for pages in site.pages %}

{{pages.url}}

{% endfor %}
```

This works fine, but has the following problems:
1. reordering the menu items requires to edit every front matter of every article and modify the order attribute
2. You have no place to see the structure of the book-bar.
# The new way

To reduce maintenance workload we have removed the breadcrumb and order attribute in each articles front matter. The new idea is to read the menu attribute from the book-bar.yml file in order to generate the bread crumb.
## Benefits
- So now it is easier to create a new article. 
- Another huge benefit of the book-bar.yml file is that you can change the order of listed articles in the menu by only editing this file. Instead if keep the menu attribute and order attrribute in each article, you would need to modify each article.
- The book-bar.yml file also shows the article hierarchy of the respective board. This is often useful during creation of articles or for documentation purposes
# Generating the Bread Crumb
## two step procedure
1. get the data for the bread crumb
2. Generate the HTML code for the bread crumb
## Problem to solve

Nested for loops did not work
# References
- https://jekyllrb.com/docs/variables/
- https://help.shopify.com/themes/liquid/objects/for-loops
- http://stackoverflow.com/questions/9612235/what-are-some-good-ways-to-implement-breadcrumbs-on-a-jekyll-site
- http://stackoverflow.com/questions/22167297/breadcrumbs-in-liquid
- http://stackoverflow.com/questions/8863469/liquid-for-loop-not-working-properly-in-jekyll
- http://stackoverflow.com/questions/33534739/liquid-nesting-for-loop-syntax-issue-in-jekyll
## Related Issues
- → #42 
- → #47

**Comment by VillageHubertChen** [comment]
Works great! Thanks for being tough and keep working at it until success, so that creating new articles and maintaining them is much easier.
